# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "XMrMD5l7UtxlUACMDZRmTZZ10FkAoC+tcl7b3ntJ/MLIkgzCMsKzpZ7fo3GFwRCz7R9kUe4XpTw9y/1msNbuId2epgI8XJ1QXJnzdKPk6OEZDAg+3OnP+WbRnGegJxq1hiIYfD4oDk7qgYtLGhJG22TFY9LpJY0HBteQiB27Tv3/N/tx61zOraX1LqZD3qHlZPzMU7GYOu3/LdY7+3XgG7Y0M/QUYcdyskwBURAUkKS8il+5ZX2MA/9TGyFKCU5LVUcy6MIScnXysZ8Om3gPZAH+ZiO6Oy69TpG75uRaWTC0y9EyqlUSZvLedcQnW+TU59V7/NUB6lVVDrrSSkZqJR4IC5WV75LYaEaEKSlvUDxsXdm3NiP+fg5rKvUMW/NKwl73BYbuygat1/vTARtKc2GbDIND4fyuPXUiEr8cveS/iXgDl71S641i1IMGFRZ2/gbbwg3XOU3o2rr2Palgn7v/x7uq6UbujLSLK7vhfriMPrjh9VRZzdXiaer3wZCoul3PI62CXRIOk+nZTzBoMqIP3lwtxnzMMKii7+7yEbngsNBDgUo0yvHLXEDbSFUpsjZkOoD0BP+mkB0v35oF9PvvFE6DGkxpZlcOCHEF5UnvQMwVHLoiBSaIMbg5wnwa2bn37YnYV0HuzGoghN+x7KZDPhg6F5wme8LvI3Q+Dmg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
