travis:
  secure:
    BINSTAR_TOKEN: XMrMD5l7UtxlUACMDZRmTZZ10FkAoC+tcl7b3ntJ/MLIkgzCMsKzpZ7fo3GFwRCz7R9kUe4XpTw9y/1msNbuId2epgI8XJ1QXJnzdKPk6OEZDAg+3OnP+WbRnGegJxq1hiIYfD4oDk7qgYtLGhJG22TFY9LpJY0HBteQiB27Tv3/N/tx61zOraX1LqZD3qHlZPzMU7GYOu3/LdY7+3XgG7Y0M/QUYcdyskwBURAUkKS8il+5ZX2MA/9TGyFKCU5LVUcy6MIScnXysZ8Om3gPZAH+ZiO6Oy69TpG75uRaWTC0y9EyqlUSZvLedcQnW+TU59V7/NUB6lVVDrrSSkZqJR4IC5WV75LYaEaEKSlvUDxsXdm3NiP+fg5rKvUMW/NKwl73BYbuygat1/vTARtKc2GbDIND4fyuPXUiEr8cveS/iXgDl71S641i1IMGFRZ2/gbbwg3XOU3o2rr2Palgn7v/x7uq6UbujLSLK7vhfriMPrjh9VRZzdXiaer3wZCoul3PI62CXRIOk+nZTzBoMqIP3lwtxnzMMKii7+7yEbngsNBDgUo0yvHLXEDbSFUpsjZkOoD0BP+mkB0v35oF9PvvFE6DGkxpZlcOCHEF5UnvQMwVHLoiBSaIMbg5wnwa2bn37YnYV0HuzGoghN+x7KZDPhg6F5wme8LvI3Q+Dmg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
